### PR TITLE
Correcting script used by temp-patch-olm.sh script

### PR DESCRIPTION
**Pull request by thomas-mattsson**

### CODE REVIEW

**Review by fketelaars — COMMENTED** [review]
Is the temporary patching of OLM still needed? I believe that as from OCP 4.10.54, the OLM issues in OpenShift disappeared. If no longer needed, I would rather remove the patching script altogether.

**Comment by fketelaars** [comment]
@thomas-mattsson ^^?

**Comment by thomas-mattsson** [comment]
@fketelaars, uncertain, but since this can not have been executed on any new installs for quite a while it seems like it's now redundant. I can update the PR to delete it all together.

**Comment by fketelaars** [comment]
@thomas-mattsson Yes please.

**Review by fketelaars — APPROVED** [review]

**Pull request merged**
